FROM resin/%%RESIN_MACHINE_NAME%%-alpine-node:8.9.4-20180302

WORKDIR /usr/src/app

RUN apk add --no-cache screen

COPY package.json package-lock.json ./
RUN npm install --only=production
COPY testrun.sh ./
COPY src ./src

CMD ["bash", "testrun.sh"]
