FROM resin/%%RESIN_MACHINE_NAME%%-alpine-node:9.2.1-slim-20180203

WORKDIR /usr/src/app

RUN apk add --no-cache screen

COPY package.json .
RUN npm install --production
COPY . ./

CMD ["bash", "testrun.sh"]
